language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - flake8 ./
  - py.test --cov . --cov-config .coveragerc

after_success:
  - coveralls --rcfile=.coveragerc

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
